services:
  - type: web
    name: binzolife
    runtime: docker
    repo: https://github.com/kostrikin552-hub/BinzoLife
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    numReplicas: 1   # <--- ОБЯЗАТЕЛЬНО: только один экземпляр
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PROVIDER_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: INTERNAL_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 8000
      - key: LOG_LEVEL
        value: INFO
      - key: WEB_CONCURRENCY   # <--- ограничиваем количество воркеров до 1
        value: 1
