services:
  - type: web
    name: binzolife
    runtime: docker
    repo: https://github.com/kostrikin552-hub/BinzoLife
    plan: starter   # Рекомендую перейти на платный тариф для стабильности
    region: frankfurt
    dockerfilePath: ./Dockerfile
    numReplicas: 1
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PROVIDER_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: INTERNAL_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: YANDEX_GEOCODER_API_KEY
        sync: false
      - key: PORT
        value: 8000
      - key: LOG_LEVEL
        value: INFO
      - key: WEB_CONCURRENCY
        value: 1
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: binzolife
          property: host
